---
- hosts: hub_west
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install MOTD
      copy:
        src: resources/motd.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Create user
      user:
        name: hacker
        group: sudo
        # Created with mkpasswd --method=sha-512. Cleartext is "hackybirthday"
        password: "$6$eognPI9yeV8CiQ7.$8qMcpIeLXxyNWgkEAaiJeOWVMInnEPExnjd.EimPUC9FnJQJf0Zn599WSY3m6le192LPx6lgYezhM3ib71Sxu0"
        create_home: yes
        shell: /bin/bash
    - name: Configure sshd
      copy:
        src: resources/password_sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        mode: '0644'
    - name: Restart sshd
      service:
        name: ssh
        state: restarted
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Create website
      copy:
        src: resources/west_index.html
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0644'
    - name: Install nmap
      apt:
        name: nmap
        state: present
    - name: Install midnight notes file
      copy:
        src: resources/midnight_notes.txt
        dest: /home/hacker/midnight_notes.txt
        owner: hacker
        mode: '0644'
- hosts: hub_south
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install MOTD
      copy:
        src: resources/messwith_motd.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Install telnet
      apt:
        name: telnetd
        state: present
        update_cache: yes
    - name: Create user
      user:
        name: mantic0re
        comment: MANTIC0RE
        group: sudo
        # Created with mkpasswd --method=sha-512. Cleartext is "zxcvbnm"
        password: "$6$DsEhGC.UVk$rtICpUQQ8m8tG.jxRhGyA9jsnwI9F4g1pBz8uLKbv.Pk7q/Itni.gqvwsoX6IXv3/Y.ndB13STJn7uWmcuDcv/"
        create_home: yes
        shell: /bin/bash
    - name: Create user .ssh dir
      file:
        path: /home/mantic0re/.ssh
        state: directory
    - name: Create user known_hosts
      copy:
        src: resources/south_known_hosts
        dest: /home/mantic0re/.ssh/known_hosts
        owner: mantic0re
        mode: '0600'
    - name: Upload INSTRUCTIONS file
      copy:
        src: resources/INSTRUCTIONS
        dest: /home/mantic0re/INSTRUCTIONS
        owner: mantic0re
        mode: '0644'
- hosts: hub_core
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install MOTD
      copy:
        src: resources/evil_motd.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Create gh0stc0re user
      user:
        name: gh0stc0re
        create_home: yes
    - name: Upload game key
      copy:
        src: resources/game_key
        dest: /home/gh0stc0re/CAT_ME_TO_WIN
        owner: root
        group: root
        mode: '0600'
    - name: Install xinetd
      apt:
        name: xinetd
        state: present
        update_cache: yes
    - name: Create ftp user
      user:
        name: ftp
        comment: ftp user
    - name: Create chroot dir
      file:
        path: /usr/share/empty
        state: directory
    - name: Create vsftpd conf
      copy:
        src: resources/vsftpd.conf
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: '0644'
    - name: Upload vsftpd binary
      copy:
        src: resources/vsftpd
        dest: /usr/local/sbin/vsftpd
        owner: root
        group: root
        mode: '0755'
    - name: Upload xinetd conf
      copy:
        src: resources/xinetd.d-vsftpd
        dest: /etc/xinetd.d/vsftpd
        owner: root
        group: root
        mode: '0644'
    - name: Restart xinetd
      service:
        name: xinetd
        state: restarted
